import Footer from '@/components/Footer';
import Sidebar from '@/components/Sidebar';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../styles/tailwind.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn([inter.className, 'flex'])}>
        <Sidebar />
        <div className='min-h-dvh w-full flex flex-col overflow-scroll'>
          <div className='flex-1'>{children}</div>
          <Footer />
        </div>
        <div id='modal'></div>
      </body>
    </html>
  );
}
