import Footer from '@/components/Footer';
import Sidebar from '@/components/Sidebar';
import type { Metadata } from 'next';
import '../../styles/tailwind.css';
import Provider from './Provider';

export const metadata: Metadata = {
  title: '패킷',
  description: 'Generated by create next app',
  icons: '/logo.svg',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/logo.svg' />
      </head>
      <body className='flex'>
        <Provider>
          <Sidebar />
          <div className='min-h-dvh w-full flex flex-col overflow-scroll styled-scroll'>
            <div className='flex-1'>{children}</div>
            <Footer />
          </div>
          <div id='modal' className='styled-scroll'></div>
        </Provider>
      </body>
    </html>
  );
}
